import os
import sys

# Add dandy-gb/tools to path to import compression functions
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../dandy-gb/tools")))

try:
    import verify_compression as vc
except ImportError as e:
    print(f"Error importing verify_compression: {e}")
    sys.exit(1)

def generate_header():
    # 1. All Spaces map (inner tiles = 0)
    all_spaces_inner = [0] * 1624
    all_spaces_flat = vc.reconstruct_edge_walls(all_spaces_inner)
    all_spaces_comp = vc.scheme_b2_compress(all_spaces_inner)
    
    # 2. All Walls map (inner tiles = 1)
    all_walls_inner = [1] * 1624
    all_walls_flat = vc.reconstruct_edge_walls(all_walls_inner)
    all_walls_comp = vc.scheme_b2_compress(all_walls_inner)
    
    # 3. Max Density map (inner tiles = 15)
    max_density_inner = [15] * 1624
    max_density_flat = vc.reconstruct_edge_walls(max_density_inner)
    max_density_comp = vc.scheme_b2_compress(max_density_inner)
    
    # 4. Truncated bitstream (only 5 bytes)
    truncated_comp = [0x11, 0x22, 0x33, 0x44, 0x55]
    
    # 5. Extremely long bitstream (Max density + 1000 extra bytes of 0xFF)
    long_comp = max_density_comp + [0xFF] * 1000
    
    # 6. Completely empty/zero bitstream (1 byte of 0)
    empty_comp = [0x00]
    
    # Write to header file
    header_path = os.path.join(os.path.dirname(__file__), "test_cases.h")
    print(f"Writing test cases to {header_path}...")
    
    with open(header_path, "w") as f:
        f.write("/* Generated by generate_test_cases.py. Do not edit. */\n\n")
        f.write("#ifndef TEST_CASES_H\n")
        f.write("#define TEST_CASES_H\n\n")
        f.write("#include <stdint.h>\n\n")
        
        def write_array(name, data):
            f.write(f"const uint8_t {name}[] = {{\n")
            hex_strs = [f"0x{b:02X}" for b in data]
            for i in range(0, len(hex_strs), 12):
                f.write("    " + ", ".join(hex_strs[i:i+12]) + ",\n")
            f.write("};\n\n")
            
        write_array("case_all_spaces", all_spaces_comp)
        write_array("case_all_walls", all_walls_comp)
        write_array("case_max_density", max_density_comp)
        write_array("case_truncated", truncated_comp)
        write_array("case_long", long_comp)
        write_array("case_empty", empty_comp)
        
        # Define the pointer array with 26 elements as required by levels.h
        f.write("const uint8_t* const custom_levels[26] = {\n")
        f.write("    case_all_spaces,  /* Level 0 */\n")
        f.write("    case_all_walls,   /* Level 1 */\n")
        f.write("    case_max_density, /* Level 2 */\n")
        f.write("    case_truncated,   /* Level 3: SHOULD NOT CRASH */\n")
        f.write("    case_long,        /* Level 4: SHOULD NOT OVERFLOW */\n")
        f.write("    case_empty,       /* Level 5: SHOULD NOT CRASH */\n")
        # Pad the rest of the 26 levels with case_all_spaces
        for i in range(6, 26):
            f.write("    case_all_spaces,\n")
        f.write("};\n\n")
        f.write("#endif /* TEST_CASES_H */\n")
        
    print("Test cases generated successfully!")

if __name__ == "__main__":
    generate_header()
